dist: xenial
language: java

cache:
  directories:
    - "$HOME/.m2"
    - "$HOME/.sonar"

before_cache:
  - rm -rf $HOME/.m2/repository/com/twa/flights

script: 
  - mvn clean verify

jdk: 
  - openjdk11

os:
  - linux
